name: call reusable workflow
on:
  workflow_dispatch:
  
jobs:
  call-reusable-workflow:
    permissions:
      contents: read
      pull-requests: read
    uses: efi-rfauzan/reusable-workflow/.github/workflows/reusable-workflow.yaml@main
    
